### PR TITLE
Feature accounting

### PR DESCRIPTION
**Pull request by philippreston**
Added the accounting feature into fifo.

```
fifo -c dev orgs accounting 798c5e77-b623-4dd4-bf5a-d6db9b2603ff 1451606400000000 1453807249986000
                       Resource UUID Action   Timestamp        
------------------------------------ -------- ---------------- 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d create   1440010933711914 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d update   1440082303097810 
c6ca867f-b309-472b-b94e-7608853af16c create   1440082358865496 
c074a7b3-cd88-48e5-95fd-4338a0945743 create   1440085642941763 
27880935-50b6-47a6-bc10-cb2fe70cc521 create   1440086213866154 
27880935-50b6-47a6-bc10-cb2fe70cc521 update   1440086904744407
```

Also added  --readable option for displaying human readable date and time

```
fifo -c dev orgs accounting --readable 798c5e77-b623-4dd4-bf5a-d6db9b2603ff 1451606400000000 1453807249986000
                       Resource UUID Action   Date & Time         
------------------------------------ -------- ------------------- 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d create   2015/08/19 20:02:13 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d update   2015/08/20 15:51:43 
c6ca867f-b309-472b-b94e-7608853af16c create   2015/08/20 15:52:38 
c074a7b3-cd88-48e5-95fd-4338a0945743 create   2015/08/20 16:47:22 
27880935-50b6-47a6-bc10-cb2fe70cc521 create   2015/08/20 16:56:53
```

Minor change to curl print to allow easier copy, paste and run

### CODE REVIEW

**Comment by Licenser** [comment]
Hi Phil,
love the accounting output but (there is always a but) not the readable flag, there is a facility to have different fields (`--fmt`) already instead of adding a new flag both should be valid fields i.e.:

```
fifo -c dev orgs accounting --fmt resource,action,data 798c5e77-b623-4dd4-bf5a-d6db9b2603ff 1451606400000000 1453807249986000
                       Resource UUID Action   Date & Time         
------------------------------------ -------- ------------------- 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d create   2015/08/19 20:02:13 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d update   2015/08/20 15:51:43 
c6ca867f-b309-472b-b94e-7608853af16c create   2015/08/20 15:52:38 
c074a7b3-cd88-48e5-95fd-4338a0945743 create   2015/08/20 16:47:22 
27880935-50b6-47a6-bc10-cb2fe70cc521 create   2015/08/20 16:56:53
```

and

```
fifo -c dev orgs accounting --fmt resource,action,timestamp 798c5e77-b623-4dd4-bf5a-d6db9b2603ff 1451606400000000 1453807249986000
                       Resource UUID Action   Timestamp        
------------------------------------ -------- ---------------- 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d create   1440010933711914 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d update   1440082303097810 
c6ca867f-b309-472b-b94e-7608853af16c create   1440082358865496 
c074a7b3-cd88-48e5-95fd-4338a0945743 create   1440085642941763 
27880935-50b6-47a6-bc10-cb2fe70cc521 create   1440086213866154 
27880935-50b6-47a6-bc10-cb2fe70cc521 update   1440086904744407
```

I'm also kind of think named parameters for start end end would be nicer to make it easier to read (for example):

`fifo -c dev orgs accounting --fmt resource,action,data 798c5e77-b623-4dd4-bf5a-d6db9b2603ff --start 1451606400000000 --end 1453807249986000`

or

`fifo -c dev orgs accounting --fmt resource,action,data 798c5e77-b623-4dd4-bf5a-d6db9b2603ff -s 1451606400000000 -e 1453807249986000`

with would also allow using the option to use dates:

`fifo -c dev orgs accounting --fmt resource,action,data 798c5e77-b623-4dd4-bf5a-d6db9b2603ff --start-date '2015-08-19 20:02:13' -e '2015-08-20 16:56:53'`

Now last but not least I prefer ISO dates as they are well defined and a global standard.

I know lots of opinion here ;)

**Comment by philippreston** [comment]
--fmt is much cleaner way to do it :-)

Changes made (as well as other stuff mentioned)

**Comment by philippreston** [comment]
Example output with flags, date in fmt and using date and time to set range
```
fifo --curl -c dev orgs accounting --fmt resource,action,date 798c5e77-b623-4dd4-bf5a-d6db9b2603ff -s "2015-01-01 00:00:00" -e "2016-02-09 00:00:00"
> [curl] curl -X GET "http://192.168.221.201/api/2/sessions/vULQyPBlzjUo7Ts2y6N97UMLDdRJmbox" -H "content-type:application/json;charset=UTF-8" -H "accept:application/json"   
> [curl] curl -X POST "http://192.168.221.201/api/2/oauth/token" -H "content-type:application/json;charset=UTF-8" -H "accept:application/json" -d "username=ppreston%40lucera.com&password=2wsx%40WSX&grant_type=password"  
> [curl] curl -X GET "http://192.168.221.201/api/2/orgs/798c5e77-b623-4dd4-bf5a-d6db9b2603ff/accounting?start=1420070400000000&end=1454976000000000" -H "content-type:application/json;charset=UTF-8" -H "authorization:Bearer 8ko4m5xJ66je1ik6SYAdIEe1TxFWQh8q" -H "accept:application/json"   
                       Resource UUID Action   Date & Time         
------------------------------------ -------- ------------------- 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d create   2015-08-19 20:02:13 
676cfb7e-44ec-4fdf-916d-eaa5e2fcfb3d update   2015-08-20 15:51:43 
c6ca867f-b309-472b-b94e-7608853af16c create   2015-08-20 15:52:38 
c074a7b3-cd88-48e5-95fd-4338a0945743 create   2015-08-20 16:47:22
```

**Comment by Licenser** [comment]
that looks awesome! thanks mate

**Pull request merged**
