### PR TITLE
Added --raw to Lists

### PR DESCRIPTION
**Pull request by philippreston**
Added --raw/-r flag to lists to allow output of an array of all JSON objects for the entity.

### CODE REVIEW

**Comment by kevinmeziere** [comment]
IMO --json would make more sense. JSON happens to be how the data is transmitted to pyfi, but only because of the http accept header.

**Comment by Licenser** [comment]
I think --raw/-r makes sense, --json (or --msgpack) could be added later to switch the transport protocol?

But in that flag isn't mentioned in the mayflies yet, it would be nice to have that before it is merged.

**Comment by kevinmeziere** [comment]
--raw is an existing option for the 'vms' command.

**Comment by philippreston** [comment]
I added a further commit to update the man pages with the flag.

**Comment by kevinmeziere** [comment]
Philip thanks for the contribution!

**Pull request merged**
